<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_httpchimera.labs.oreilly.combooks1234_38f2da</name>
   <tag></tag>
   <elementGuidId>bfda5d76-a145-4732-bda9-7b24503a30b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#website-wrapper > div.col-md-9.col-sm-12 > #userName-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='userName-value'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>96aa87d9-ed7a-4232-9eba-e835ea7dc066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>8cdf7645-0e0a-426a-b7bb-0ce8bc9ce5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>a9e31bdf-df93-4faf-8239-befa58e3496f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userName-value</value>
      <webElementGuid>b71748c8-fdd8-4383-8969-ffe13a9122a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>http://chimera.labs.oreilly.com/books/1234000001708/index.html</value>
      <webElementGuid>e8745638-0b32-45a5-929d-aae55da40189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;website-wrapper&quot;)/div[@class=&quot;col-md-9 col-sm-12&quot;]/label[@id=&quot;userName-value&quot;]</value>
      <webElementGuid>abefb575-66cb-4919-bb3e-6e02a9fc7e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//label[@id='userName-value'])[9]</value>
      <webElementGuid>8ea931ca-15b0-401a-92d4-c3ad1db39820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='website-wrapper']/div[2]/label</value>
      <webElementGuid>2f8f34c4-40fc-4a4e-9240-13b795a44ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/label</value>
      <webElementGuid>5bbe2478-7f21-4e5d-ae5c-7f82dd332144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'userName-value' and (text() = 'http://chimera.labs.oreilly.com/books/1234000001708/index.html' or . = 'http://chimera.labs.oreilly.com/books/1234000001708/index.html')]</value>
      <webElementGuid>1d657726-7a54-4021-9d15-99c726838345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
