<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Welcome,Login in Book StoreUserName  P_1bd0cd</name>
   <tag></tag>
   <elementGuidId>c570eb46-5636-4333-80f9-42ee78c30590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userForm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='userForm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>6f0fef21-2304-422a-a1c2-08df55c5be7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userForm</value>
      <webElementGuid>8bb35fec-cf2d-4535-a3a9-3c1a89cadecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome,Login in Book StoreUserName : Password : LoginNew User</value>
      <webElementGuid>4b851221-e080-47ee-ac2c-10152bb020fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userForm&quot;)</value>
      <webElementGuid>a6ef0862-41de-4c88-82c3-bcf5d40379cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='userForm']</value>
      <webElementGuid>9a59084d-f86e-4a47-8559-52ecf43abbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/form</value>
      <webElementGuid>ff4758ec-133c-4f2b-8c5f-8b872712705b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>9aeaa87a-c7b3-4fd1-8b5f-82ca9defbc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'userForm' and (text() = 'Welcome,Login in Book StoreUserName : Password : LoginNew User' or . = 'Welcome,Login in Book StoreUserName : Password : LoginNew User')]</value>
      <webElementGuid>6d6d5db5-a83d-434e-9ec2-f579321b6aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
