<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_You are already logged in. View your profile</name>
   <tag></tag>
   <elementGuidId>d881f1aa-7c14-40d5-95fa-efba7510e7a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loading-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='loading-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8242f732-c8c4-4d68-998e-fae301c00719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>6f0eed55-65ab-4322-9061-e498b0af18b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loading-label</value>
      <webElementGuid>d72ca730-f7c1-4056-a35f-871911a1a903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are already logged in. View your profile.</value>
      <webElementGuid>ee73a4a7-cc7c-488e-9a75-261cae86a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loading-label&quot;)</value>
      <webElementGuid>a4dedaa5-f81f-412b-bae8-d3e3d96e636e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='loading-label']</value>
      <webElementGuid>92d6ccf3-e430-4714-9ea1-14745c6579dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='loading-wrapper']/div/label)[3]</value>
      <webElementGuid>5e6039f7-052c-4d2d-8ab2-1496fe8b6ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>677b1565-6f06-4c3a-9a10-15b941921356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'loading-label' and (text() = 'You are already logged in. View your profile.' or . = 'You are already logged in. View your profile.')]</value>
      <webElementGuid>c20f52bc-ae0e-489d-b049-8c3352dd3588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
