<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>dd2ed86c-dd33-46b2-8935-6dca09853a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeSmallModal-ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35a12658-64a2-44b7-a91b-f0a378f5635a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal-ok</value>
      <webElementGuid>335303d1-379e-4102-864f-baf223809306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5264eb9b-d324-4faa-9cf1-ccfb9d0d619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>f240c46f-1f32-4a4b-ae61-b814529b4635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>babddac9-52b2-45fa-bf45-cecf79f4495b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeSmallModal-ok&quot;)</value>
      <webElementGuid>4fd21fc3-1790-4734-b08c-14ff47713f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeSmallModal-ok']</value>
      <webElementGuid>071052e4-ee1e-4e2e-8549-4a6c66048df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/button</value>
      <webElementGuid>6291249d-738e-4baa-9aaa-14ed7db343fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal-ok' and @type = 'button' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>74753040-fec6-4dda-b521-d73ddb73f72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
