<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delet</name>
   <tag></tag>
   <elementGuidId>aa6ddef7-573c-4d01-b68d-bd927d1a036a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rt-tr.-even > div.rt-td > div.action-buttons > #delete-record-undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='delete-record-undefined'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f8dec1b0-5569-49fa-80a4-33fe0bb0cddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete-record-undefined</value>
      <webElementGuid>17908d4c-9cfd-46c6-b98b-94e9a7b22fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>83a34149-8500-436c-8fd3-383bc0e727fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>ece94cab-0fd7-433d-b50f-7eda9173ba77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;body-height&quot;]/div[@class=&quot;container playgound-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mt-4 col-md-6&quot;]/div[@class=&quot;profile-wrapper&quot;]/div[@class=&quot;ReactTable -striped -highlight&quot;]/div[@class=&quot;rt-table&quot;]/div[@class=&quot;rt-tbody&quot;]/div[@class=&quot;rt-tr-group&quot;]/div[@class=&quot;rt-tr -even&quot;]/div[@class=&quot;rt-td&quot;]/div[@class=&quot;action-buttons&quot;]/span[@id=&quot;delete-record-undefined&quot;]</value>
      <webElementGuid>0fa05670-72e4-466e-b4f4-bac04c626963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='delete-record-undefined'])[2]</value>
      <webElementGuid>78bc29a5-9461-46a0-97b5-acff55860455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/div[5]/div/span</value>
      <webElementGuid>f06a46e1-a279-4456-a6f2-8033299cc525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/div/span</value>
      <webElementGuid>a22981ad-7f81-4b5d-9ed8-cae7a8a42de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'delete-record-undefined' and @title = 'Delete']</value>
      <webElementGuid>8f016e7e-1491-4fdb-a28b-deae9b7bd153</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
