<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Name  test123Log out</name>
   <tag></tag>
   <elementGuidId>7cd69e6f-7426-4f59-bf82-e55e32c40a18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7dc3caf7-f846-40d8-8a35-c8c968482263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-wrapper</value>
      <webElementGuid>9e5d7090-e4ba-4768-99a4-716845681ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 justify-content-end row</value>
      <webElementGuid>2e17e38e-0671-40b3-a44d-e9a0f10e9ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name : test123Log out</value>
      <webElementGuid>bad54bea-2f18-4fa0-a163-e015580c7117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-wrapper&quot;)</value>
      <webElementGuid>1edc3fbf-44c2-4fbe-8a84-67a2b6c140db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login-wrapper']</value>
      <webElementGuid>e1915ab0-56f3-433d-befb-278a6ce03f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>452e0762-5631-4055-99b8-05076e03fbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div</value>
      <webElementGuid>22169a50-17e6-4162-a91d-5965a26e323c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login-wrapper' and (text() = 'User Name : test123Log out' or . = 'User Name : test123Log out')]</value>
      <webElementGuid>96bae645-129b-4d9d-81fa-4b39b183a3e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
